/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DeployMasterChain } from "./DeployMasterChain";
export type { DeploySatelliteChain } from "./DeploySatelliteChain";
