/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DeployMasterChain__factory } from "./DeployMasterChain__factory";
export { DeploySatelliteChain__factory } from "./DeploySatelliteChain__factory";
