/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Communicator } from "./Communicator";
export type { IMessageRecipient } from "./IMessageRecipient";
export type { IOutbox } from "./IOutbox";
