/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as communicatorSol from "./Communicator.sol";
export type { communicatorSol };
import type * as tokens from "./tokens";
export type { tokens };
export type { Core } from "./Core";
export type { ILido } from "./ILido";
export type { Satellite } from "./Satellite";
