/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IController } from "./IController";
export type { IERC20 } from "./IERC20";
export type { IERC20Upgradeable } from "./IERC20Upgradeable";
export type { IFutureVault } from "./IFutureVault";
export type { IFutureWallet } from "./IFutureWallet";
export type { IRegistry } from "./IRegistry";
