/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Communicator__factory } from "./Communicator__factory";
export { IMessageRecipient__factory } from "./IMessageRecipient__factory";
export { IOutbox__factory } from "./IOutbox__factory";
